# Generated by Django 2.2.5 on 2019-09-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_key',
        ),
    ]
