# Generated by Django 2.2.5 on 2019-10-03 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20191001_0602'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blog',
            unique_together={('title', 'name')},
        ),
    ]
